### ISSUE TITLE
Check if data in series is string but in dateformat

### ISSUE THREAD

**Issue by galbraun** [dovpanda-dev/dovpanda#37]
# Basic Functionality
Check after a Series or Dataframe creation and after addition of a new column if the data look like datetime but in a different dtype.

# Hooks Upon

- [x] Series / Dataframe creation functions
- [x] assign
- [x] insert
- [x] _setitem

# Hook Type

per-hook 

# Design
check that the data inserted into the structure is with date structure (with the help of python-dateutil), if the dtype is not date - suggest using `pandas.to_datetime()`

**Comment by DeanLa** [comment]
Maybe also should hook upon read methods?

**Comment by DeanLa** [comment]
We should make the option for same function to hook several functions.

**Comment by DeanLa** [comment]
addressed in #39

**Comment by DeanLa** [comment]
On it
