### ISSUE TITLE
Add a hint in case of large csv files to add nrows=10, when a call to 'read_csv' is being executed

### ISSUE THREAD

**Issue by tzurE** [dovpanda-dev/dovpanda#57]
# Basic Functionality
When loading large csv files (100K lines at least), we should recommend the user to add 
`nrows=10`, so they can check that the types and formatting of the csv file fits their demands.

# Hooks Upon

read_csv

# Hook Type

# Brief Description
pre-hook

# Design

**Comment by tzurE** [comment]
filesize can vary. What would you say is a filesize that should be checked?

**Comment by DeanLa** [comment]
How do you plan to know the how many line are in the file?

**Comment by DeanLa** [comment]
My inconvenience with this is as follows: dovpanda should never block the user. If they asked for read csv, no matter how many rows, they should get it eventually. The hint could jump before then, but it is not helpful for current runtime, so it's more of a "general" hint for next times.
Think how you phrase that.

**Comment by tzurE** [comment]
Basic idea I had in mind is counting the rows before opening the file, and giving an option to continue with the file.
But if the decision is that dovpanda should never block the user, then I need to rethink how to give the information in a way that won't block the user.

**Comment by DeanLa** [comment]
if you are doing a pre-hook, it wont' block the user just print before loading. That's fine. but phrasing is important.
How would you count lines before pd.read_csv?

**Comment by tzurE** [comment]
I can read a file in 0.4 secs using a buffer reading function - I read a chunk of the file(1024? 1024*1024? need to check), and count the number of '\n' I see in that chunk.
you can see an example here:
https://stackoverflow.com/questions/845058/how-to-get-line-count-cheaply-in-python

**Comment by DeanLa** [comment]
Maybe consider looking at the file size instead of lines? maybe use `shutil` to just do `wc -l`?
anyway, go for it.
