### ISSUE TITLE
[HINT] When saving a dataframe to text format, suggest ziping

### ISSUE THREAD

**Issue by DeanLa** [dovpanda-dev/dovpanda#60]
# Basic Functionality
if saved filesize is big, suggest zipping "on the fly" like [in tip 10 here](https://realpython.com/python-pandas-tricks/#10-write-pandas-objects-directly-to-compressed-format)

# Hooks Upon

write methods that are text (json, csv)
# Hook Type

post
# Design

use functionality of get size similar to #58

**Comment by ddofer** [comment]
Is there already one about not creating an index col (index=False)? + gzip is typically the best compression option for max compatability and pandas support.
