### ISSUE TITLE
[HINT] hint when df=df.dropna(inplace=True) is causing df=None

### ISSUE THREAD

**Issue by itamar-precog** [dovpanda-dev/dovpanda#62]
# Basic Functionality
df.dropna(inplace=False) returns the modified dataframe. When changing to inplace=True, it's easy to forget to remove the "df= " at the beginning - so it's a useful hint...

# Hooks Upon

# Hook Type
pre-hook

# Design
I don't know... maybe just notice that the df is assigned None?

**Comment by itamar-precog** [comment]
Maybe there should also be a general hint against df=df.method(inplace=False), suggesting to replace it with df.method(inplace=True)?

**Comment by DeanLa** [comment]
Great idea

**Comment by DeanLa** [comment]
implemented for next release
